var logo_str = Array(
  '',
  '            O',
  '           CCCCC0',
  '             CCCCCCG',
  '                CCCCCCC',
  '                   OCCCCCC',
  '                       CCCCCC',
  '                          CCCCCC',
  '                            8CCCCC',
  '                               CCCCC8',
  '                                 CCCCC',
  '            GCCCCCCCCCC8           CCCCO',
  '        8CCCCCCCCCCCCCCCCCC         CCCCO',
  '      OCCCCCG          CCCCCC        CCCC8',
  '     CCCCC                CCCC8       CCCC',
  '    CCCC                   CCCC       0CCC0',
  '   CCCC         8CCC8       CCCC       CCCC',
  '  OCCC8       OCCCCC8       CCCC       CCCC',
  '  CCCC       OCCCC          CCCC       CCCC',
  '  CCCC       CCCC          CCCCO      0CCC0',
  '  GCCC       8CCCC       CCCCC0       CCCC',
  '   CCCC       8CCCCCCCCCCCCCC        CCCC0',
  '   OCCC0         CCCCCCCCC          CCCCO',
  '    GCCCG                         8CCCC0',
  '     8CCCC                       CCCCC',
  '       CCCCCG                 CCCCCC8',
  '         CCCCCCCCO8     0GCCCCCCCC',
  '            CCCCCCCCCCCCCCCCCCG',
  '                 0GCCCCCO8').join('\n');

  module.exports = logo_str;
